### ISSUE TITLE
Setting users_id of cart fails silently?

### ISSUE THREAD

**Issue by murwiz** [interchange/Interchange6#24]
In my code I have this:

        debug 'cart identified for ', $users_id;
        shop_cart->users_id( $users_id );
        debug 'cart has ', shop_cart->users_id;

Unfortunately, the value output in the second debug statement doesn't match the first.

**Comment by SysPete** [comment]
Some changes (not all in cpan release yet) address this issue completely:
- users_id is now read-only with writer 'set_users_id' so above code will cause an exception.
- As from commit 995bedcc8e8 the cart is cached during request lifetime rather than reloaded from DB each time 'cart' or 'shop_cart' DSL is called.
